name: schulplaner_addons
description: Simply the flutter workflow:)
version: 0.1.0
author: Felix Weuthen
homepage:
publish_to: none

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  schulplaner_widgets:
    path: ../schulplaner_widgets
  schulplaner_translations:
    path: ../schulplaner_translations
  bloc:
    path: ../bloc
  #GENERAL
  uuid: 2.2.2
  #FILES AND IMAGES
  cached_network_image: 2.4.1
  path_provider: ^1.6.24
  image: ^2.1.19
  image_cropper: ^1.3.1
  flutter_image_compress: ^0.7.0
  image_picker: ^0.6.7+17
  file_picker: ^2.1.2
  photo_view: ^0.10.3
  #FIREBASE
  firebase_storage: ^5.2.0
  cloud_firestore: 0.14.4
  #MORE
  url_launcher: 5.7.10
  universal_io: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  intl_translation:
    git:
      url: https://github.com/Zazo032/intl_translation.git
      ref: patch-1


flutter: