name: schulplaner_navigation
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">2.0.0"

dependencies:
  bloc:
    path: ../bloc
  schulplaner_widgets:
    path: ../schulplaner_widgets
  schulplaner_translations:
    path: ../schulplaner_translations
  rxdart: ^0.27.0
  shared_preferences: 2.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
