name: schulplaner8
description: An all-in-one open-source school-planner app for Android, iOS, ChromeOS and the web!
publish_to: none
version: 10.0.1+611

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  schulplaner_addons:
    path: ../packages/schulplaner_addons
  schulplaner_widgets:
    path: ../packages/schulplaner_widgets
  bloc:
    path: ../packages/bloc
  authentification:
    path: ../packages/authentification
  universal_commons:
    path: ../packages/universal_commons
  schulplaner_translations:
    path: ../packages/schulplaner_translations
  date:
    path: ../packages/date
  app_functions:
    path: ../packages/app_functions
  schulplaner_functions:
    path: ../packages/schulplaner_functions
  schulplaner_models:
    path: ../packages/schulplaner_models
  schulplaner_navigation:
    path: ../packages/schulplaner_navigation
  schulplaner_website:
    path: ../schulplaner_website
  export_user_data_client:
    path: ../packages/export_user_data/export_user_data_client
  export_user_data_client_implementation:
    path: ../packages/export_user_data/export_user_data_client_implementation
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: 2.0.7
  cupertino_icons: 1.0.3

  #GOOGLE
  cloud_firestore: 2.5.1
  firebase_auth: 3.1.0
  firebase_messaging: 10.0.6
  firebase_storage: 10.0.3
  firebase_analytics: ^8.3.1
  firebase_database: 7.2.1
  firebase_performance: 0.7.0+9
  firebase_crashlytics: 2.2.1
  firebase_dynamic_links: ^2.0.9

  intl: ^0.17.0
  intl_translation: 0.17.10+1
  rxdart: ^0.27.1
  flutter_dotenv: ^5.0.2
  
  community_material_icon: 5.9.55
  font_awesome_flutter: ^9.1.0
  color: 3.0.0
  flutter_colorpicker: 0.5.0
  string_similarity: ^2.0.0
  qr_flutter: 4.0.0
  device_info_plus: 2.1.0
  url_launcher: 6.0.9
  decimal: 1.3.0
  share: 2.0.4
  tuple: 2.0.0
  launch_review: 3.0.1
  flutter_image_compress: 1.1.0
  photo_view: 0.12.0
  path_provider: 2.0.2
  cached_network_image: 3.1.0
  flutter_cache_manager: 3.1.2
  auto_size_text: 3.0.0-nullsafety.0
  filesize_ns: ^1.1.0
  image: 3.0.2
  dots_indicator: ^2.0.0
  timeago: ^3.1.0
  fl_chart: ^0.40.0
  percent_indicator: ^3.3.0-nullsafety.1
  printing: ^5.5.0
  pdf: ^3.4.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.17.0
  intl_translation:
    git:
      url: https://github.com/Zazo032/intl_translation.git
      ref: patch-1
  qr: ^2.0.0
  plugin_platform_interface: ^2.0.0
  shared_preferences: ^2.0.7
  firebase: ^9.0.1
  petitparser: ^4.0.2
  xml: ^5.0.2
  crypto: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/about_me_felix.jpg