name: authentification
description:  Authentifizierung fÃ¼r die Schulplaner App
version: 0.0.1
author: Felix Weuthen
homepage:
publish_to: none

environment:
  sdk: ">=2.11.0 <3.0.0"
  flutter: ">=1.25.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc:
    path: ../bloc
  schulplaner_widgets:
    path: ../schulplaner_widgets
  schulplaner_translations:
    path: ../schulplaner_translations
  universal_commons:
    path: ../universal_commons
  firebase_auth: 0.18.4+1
  google_sign_in: 4.5.6
  sign_in_with_apple: ^2.5.4
  firebase_auth_oauth: 0.2.2
  rxdart: ^0.24.1
  community_material_icon: 5.8.55

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  intl_translation:
    git:
      url: https://github.com/Zazo032/intl_translation.git
      ref: patch-1
      
