name: authentification
description:  Authentifizierung fÃ¼r die Schulplaner App
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">2.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc:
    path: ../bloc
  schulplaner_widgets:
    path: ../schulplaner_widgets
  schulplaner_translations:
    path: ../schulplaner_translations
  universal_commons:
    path: ../universal_commons
  firebase_auth: 3.1.0
  google_sign_in: 5.0.7
  sign_in_with_apple: ^3.0.0
  firebase_auth_oauth: 1.0.3
  rxdart: ^0.27.1
  community_material_icon: 5.9.55
  url_launcher: any
  googleapis_auth: 1.1.0
  flutter_dotenv: ^5.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.17.0
  crypto: ^3.0.0
  intl_translation:
    git:
      url: https://github.com/Zazo032/intl_translation.git
      ref: patch-1
