name: date
description: A new Flutter package project.
version: 0.0.1
author:
homepage:
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.26.0 <2.0.0"

dependencies:
  intl: ^0.17.0-nullsafety.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.17.0-nullsafety.2

flutter:
