name: schulplaner_models
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">2.0.0"

dependencies:
  authentification:
    path: ../authentification
  schulplaner_addons:
    path: ../schulplaner_addons
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.17.0
  intl_translation:
    git:
      url: https://github.com/Zazo032/intl_translation.git
      ref: patch-1
  petitparser: ^4.0.2
  xml: ^5.0.2
  crypto: ^3.0.0


flutter: